# Description.
name: Custom Object Detection Gen2 VFNet
task_type: DETECTION
task_family: VISION
instantiation: "CLASS"
summary: Custom Object Detection Model L Gen 2
application:
  ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTrainingTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdet/apis/ote/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 4
      learning_rate:
        default_value: 0.003
      learning_rate_warmup_iters:
        default_value: 1200
      num_iters:
        default_value: 10000


# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Inference options. Defined by OpenVINO capabilities, not Algo Backend or Platform.
inference_targets:
  - CPU
  - GPU
  - VPU
