# Description.
name: horizontal-text-detection-0001
task_type: DETECTION
task_family: VISION
instantiation: CLASS
summary:  Text Detection based on MobileNetV2 (FCOS).

# Algo backend.
# Would be better to have something more precise and self-contained, e.g.:  docker image or path to Python venv activation script?
framework: OTEDetection v2.9.1

dependencies:
- source: ../../../../mmdet/apis/ote/apis/detection/configuration.yaml
  destination: configuration.yaml

# Should be revisited?
application:
  ~

# Optional? requirements to the dataset. Should be revisited?
# dataset_requirements:
#   ~

# Task implementation.
entrypoints:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask

# Task and hyperparameters.
hyper_parameters:
  base_path: configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 8
      learning_rate:
        default_value: 0.01
      num_iters:
        default_value: 25

# Available model optimizations and their configuration.
# optimization:
#   output_format:
#     onnx:
#       default: true
#     openvino:
#       default: true
#       input_format: BGR
#       normalize_input: true
#       precision: FP32
#       pot: ~
#   nncf:
#     quantization:
#       config: compression_config.json
#       default: false
#     sparsity:
#       config: compression_config.json
#       default: false

# Training resources.
max_nodes: 1
training_targets:
  - GPU

# Inference options. Defined by OpenVINO capabilities, not Algo Backend or Platform.
inference_targets:
  - CPU
  - GPU

# Some meta information, which may be used for model recommendation. In general, metrics are non-static, hence has to be updated.
# metrics:
# - display_name: Size
#   key: size
#   unit: Mp
#   value: 1.95
# - display_name: Complexity
#   key: complexity
#   unit: GFLOPs
#   value: 8.0
# - display_name: F1-score
#   key: f1
#   unit: '%'
#   value: 88.45
# - display_name: Recall
#   key: recall
#   unit: '%'
#   value: 86.39
# - display_name: Precision
#   key: precision
#   unit: '%'
#   value: 90.61
# - display_name: AP @ [IoU=0.50:0.95]
#   key: ap
#   unit: '%'
#   value: 52.4